dist: trusty
sudo: required

language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php
addons:
  sonarqube:
    token:
      secure: SONAR_TOKEN # encrypted value of your token
jdk:
  - oraclejdk8

script:
  - sonar-scanner
